blog/urls.py
# coding:utf-8
"""
@author:Song Yuhang

"""
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    # 将类视图转化为函数视图。
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
    # url(r'^search/$', views.search, name='search'),
    url(r'^about/$', views.about, name='about'),
    url(r'^contact/$', views.contact, name='contact'),
]

blogproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blog.feeds import AllPostsRssFeed
from users import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('blog.urls')),
    url(r'', include('comments.urls')),
    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),
    url(r'^search/', include('haystack.urls')),
    url(r'^users/', include('users.urls')),

    # 将 auth 应用中的 urls 模块包含进来
    url(r'^users/', include('django.contrib.auth.urls')),
    url(r'^$', views.index, name='index'),
]

comments/urls.py
from django.conf.urls import url

from . import views

app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

import markdown
from django.utils.html import strip_tags

# from django.contrib.auth import get_user_model as user_model
# User = user_model()

class Category(models.Model):
    name = models.CharField(max_length=100)

    # 定义好 __str__ 方法后，解释器显示的内容为其返回值
    def __str__(self):
        return self.name

class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Post(models.Model):
    # 文章的数据库表

    title = models.CharField(max_length=70)

    body = models.TextField()

    # 文章的创建时间和最后一次修改的时间
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()

    # 文章摘要，可以没有文章摘要，但默认情况下 CharField 要求我们必须存入数据，否则就会报错。
    # 指定 CharField 的 blank=True 参数值后就可以允许空值了。
    excerpt = models.CharField(max_length=200, blank=True)

    # 我们规定一篇文章只能对应一个分类，但是一个分类下可以有多篇文章，所以我们使用的是 ForeignKey，即一对多的关联关系。
    category = models.ForeignKey(Category)

    # 而对于标签来说，一篇文章可以有多个标签，同一个标签下也可能有多篇文章，所以我们使用 ManyToManyField，表明这是多对多的关联关系。
    # 同时我们规定文章可以没有标签，因此为标签 tags 指定了 blank=True。
    tags = models.ManyToManyField(Tag, blank=True)

    # 文章作者，这里 User 是从 django.contrib.auth.models 导入的。
    # django.contrib.auth 是 Django 内置的应用，专门用于处理网站用户的注册、登录等流程，User 是 Django 为我们已经写好的用户模型。
    # 这里我们通过 ForeignKey 把文章和 User 关联了起来。
    # 因为我们规定一篇文章只能有一个作者，而一个作者可能会写多篇文章，因此这是一对多的关联关系，和 Category 类似。
    author = models.ForeignKey(User)

    # 新增 views 字段记录阅读量
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk':self.pk})

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])

    class Meta:
        ordering = ['-created_time', 'title']

    def save(self, *args, **kwargs):
        # 如果没有填写摘要
        if not self.excerpt:
            # 首先实例化一个 Markdown 类，用于渲染 body 的文本
            md = markdown.Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            # 先将 Markdown 文本渲染成 HTML 文本
            # strip_tags 去掉 HTML 文本的全部 HTML 标签
            # 从文本摘取前 54 个字符赋给 excerpt
            self.excerpt = strip_tags(md.convert(self.body))[:54]

        # 调用父类的 save 方法将数据保存到数据库中
        super(Post, self).save(*args, **kwargs)

comments/models.py
from django.db import models

class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now=True)

    post = models.ForeignKey('blog.Post')

    def __str__(self):
        return self.text[:20]

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Category, Tag
import markdown

from comments.forms import CommentForm
from django.views.generic import ListView, DetailView

from django.utils.text import slugify
from markdown.extensions.toc import TocExtension
from django.db.models import Q

# 基于类的通用视图
class IndexView(ListView):
    # 告诉 Django 获取数据库的模型是 Post。
    model = Post

    # 指定渲染的模板
    template_name = 'blog/index.html'

    # 将获得的模型数据列表保存到 post_list 里
    context_object_name = 'post_list'

    # 指定 paginate_by 属性后开启分页功能，其值代表每一页包含多少篇文章。
    paginate_by = 5

    def get_context_data(self, **kwargs):
        # 首先获得父类生成的传递给模板的字典。
        context = super().get_context_data(**kwargs)

        '''
        父类生成的字典中已有 paginator、page_obj、is_paginated 这三个模板变量，
        paginator 是 Paginator 的一个实例，page_obj 是 Page 的一个实例，
        '''
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')

        # 调用自己写的 pagination_data 方法获得显示分页导航条需要的数据。
        pagination_data = self.pagination_data(paginator, page, is_paginated)

        # 将分页导航条的模板变量更新到 context 中，注意 pagination_data 方法返回的也是一个字典。
        context.update(pagination_data)

        return context

    def pagination_data(self, paginator, page, is_paginated):
        if not is_paginated:
            # 如果没有分页，则无需显示分页导航条，不用任何分页导航条的数据，因此返回一个空的字典
            return {}

        # 当前页左边连续的页码号，初始值为空。
        left = []

        # 当前页右边连续的页码号，初始值为空。
        right = []

        # 标示第 1 页页码后是否需要显示省略号。
        left_has_more = False

        # 标示最后一页页码前是否需要显示省略号。
        right_has_more = False

        # 标示是否需要显示第 1 页的页码号。
        first = False

        # 标示是否需要显示最后一页的页码号。
        last = False

        # 获得用户当前请求的页码号
        page_number = page.number

        # 获得分页后的总页数。
        total_pages = paginator.num_pages

        # 获得整个分页页码列表。
        page_range = paginator.page_range

        if page_number == 1:
            '''
            如果用户请求的是第一页的数据，那么当前页左边的不需要数据，因此 left=[]（已默认为空）。
            此时只要获取当前页右边的连续页码号，
            比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 right = [2, 3]。
            '''
            right = page_range[page_number:page_number + 2]

            '''
            如果最右边的页码号比最后一页的页码号减去 1 还要小，
            说明最右边的页码号和最后一页的页码号之间还有其它页码，因此需要显示省略号，通过 right_has_more 来指示。
            '''
            if right[-1] < total_pages - 1:
                right_has_more = True

            '''
            如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码,
            所以需要显示最后一页的页码号，通过 last 来指示。
            '''
            if right[-1] < total_pages:
                last = True

        elif page_number == total_pages:
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]

            if left[0] > 2:
                left_has_more = True

            if left_has_more > 1:
                first = True

        else:
            '''
            用户请求的既不是最后一页，也不是第 1 页，则需要获取当前页左右两边的连续页码号，
            这里只获取了当前页码前后连续两个页码，你可以更改这个数字以获取更多页码。
            '''
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            right = page_range[page_number:page_number + 2]

            # 是否需要显示最后一页和最后一页前的省略号。
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True

            # 是否需要显示第 1 页和第 1 页后的省略号。
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True

        data = {
            'left':left,
            'right':right,
            'left_has_more': left_has_more,
            'right_has_more':right_has_more,
            'first':first,
            'last':last,
        }
        return data


def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)

    # 阅读量+1
    post.increase_views()

    post.body = markdown.markdown(post.body,
                                  extensions=[
                                      'markdown.extensions.extra',
                                      'markdown.extensions.codehilite',
                                      'markdown.extensions.toc',
                                  ])
    # 记得在顶部导入 CommentForm
    form = CommentForm()
    # 获取这篇 post 下的全部评论
    comment_list = post.comment_set.all()

    # 将文章、表单、以及文章下的评论列表作为模板变量传给 detail.html 模板，以便渲染相应数据。
    context = {'post':post,
               'form':form,
               'comment_list':comment_list
               }
    return render(request, 'blog/detail.html', context=context)

class PostDetailView(DetailView):
    # 这些属性的含义和 ListView 是一样的。
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        # 覆写 get 方法的目的是因为每当文章被访问一次，就得将文章阅读量 +1
        # get 方法返回的是一个 HttpResponse 实例。
        # 之所以需要先调用父类的 get 方法，是因为只有当 get 方法被调用后，
        # 才有 self.object 属性，其值为 Post 模型实例，即被访问的文章 post 。
        response = super(PostDetailView, self).get(request, *args, **kwargs)

        # 将文章阅读量+1。
        self.object.increase_views()

        # 视图必须返回一个 HttpResponse 对象。
        return response

    def get_object(self, queryset=None):
        # 覆写 get_object 方法的目的是因为需要对 post 的 body 值进行渲染。
        post = super(PostDetailView, self).get_object(queryset=None)
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite', # 代码高亮
            #'markdown.extensions.toc', # 自动生成目录的拓展
            TocExtension(slugify=slugify),
        ])
        post.body = md.convert(post.body)
        post.toc = md.toc
        return post

    def get_context_data(self, **kwargs):
        # 覆写 get_context_data 的目的是因为除了将 post 传递给模板外，
        # 还要把评论表单，post下的评论列表传递给模板。
        context = super(PostDetailView, self).get_context_data(**kwargs)
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update({
            'form':form,
            'comment_list':comment_list
        })
        return context


def archives(request, year, month):
    post_list = Post.objects.filter(created_time__year=year,
                                    created_time__month=month
                                    )
    return render(request, 'blog/index.html', context={'post_list':post_list})

class ArchivesView(IndexView):
    def get_queryset(self):
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        return super(ArchivesView, self).get_queryset().filter(created_time__year=year,
                                                               created_time__month=month)


class CategoryView(IndexView):
    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)


class TagView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'post_list'

    def get_queryset(self):
        tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        return super(TagView, self).get_queryset().filter(tags=tag)


def search(request):
    # 获取用户提交的搜索关键词，GET 是类似于字典的对象，所以我们取的是值，
    # 'q' 是因为表单中搜索框input的name属性的值为 q 。
    q = request.GET.get('q')
    error_msg = ''

    # 如果没有输入关键词。
    if not q:
        error_msg = '请输入关键字'
        return render(request, 'blog/index.html', {'error_msg':error_msg})

    # 如果用户输入关键词。
    # 过滤条件contains是包含关键词，前缀i表示不区分大小写。
    # Q对象用于包装查询表达式，作用是提供复杂的查询逻辑。
    post_list = Post.objects.filter(Q(title__icontains=q) | Q(body__icontains=q))
    return render(request, 'blog/index.html', {'error_msg':error_msg,
                                               'post_list':post_list})
def contact(request):
    return render(request, 'blog/contact.html')

def about(request):
    return render(request, 'blog/about.html')

templates/blog/about.html
{% extends 'base.html' %}

{% block main %}
<h1 style="color:blue">我叫宋宇航，是一名 Python 初学者。</h1>
<br><br>
<h1 style="color:green">这个是我的第一个Python项目，等到熟悉了Django框架，掌握这门技术后想往 Machine learning 上学习。学无止境嘛</h1>
<br><br>
<h1 style="color:red">希望大家能够和我多交流Django知识，<a href="{% url 'blog:contact' %}" data-hover="联系" style="color:000000">联系</a>我 </h1>
{% endblock main %}

templates/blog/contact.html
{% extends 'base.html' %}

{% block main %}
<h1 style="color:33abcd">手机：18578772127</h1>
<br><br>
<h1 style="color:blue">QQ(邮箱):503011976</h1>
<br><br>
<h1 style="color:grey">微信：syh503011976</h1>

{% endblock main %}

templates/blog/detail.html
{% extends 'base.html' %}

{% block title %}{{ post.title }} -- Django 博客教程 -- 宋小航的博客 {% endblock %}

{% block main %}
    <article class="post post-{{ post.pk }}">
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title }}</h1>
            <div class="entry-meta">
                <span class="post-category"><a href="{% url 'blog:category' post.category.pk %}">{{ post.category.name }}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date" datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                <span class="comments-link"><a href="{{ post.get_absolute_url }}#comment-area">{{ post.comment_set.count }} 评论</a></span>
                <span class="views-count"><a href="#">{{ post.views }}阅读</a> </span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ post.body|safe }}
            <br><br>
            <div class="widget-tag-cloud">
                <ul>
                    标签：
                    {% for tag in post.tags.all %}
                        <li><a href="{% url 'blog:tag' tag.pk %}" ># {{ tag.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </article>
    <section class="comment-area" id="comment-area">
        <hr>
        <h3>发表评论</h3>
        <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-4">
                    <label for="{{ form.name.id_for_label }}">名字：</label>
                    {{ form.name }}
                    {{ form.name.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.email.id_for_label }}">邮箱：</label>
                    {{ form.email }}
                    {{ form.email.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.url.id_for_label }}">网址：</label>
                    {{ form.url }}
                    {{ form.url.errors }}
                </div>
                <div class="col-md-12">
                    <label for="{{ form.url.id_for_label }}">评论：</label>
                    {{ form.text }}
                    {{ form.text.errors }}
                    <button type="submit" class="comment-btn">发表</button>
                </div>
            </div>    <!-- row -->
        </form>


        <div class="comment-list-panel">
            <h3>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h3>
            <ul class="comment-list list-unstyled">
                {% for comment in comment_list %}
                <li class="comment-item">
                    <span class="nickname">{{ comment.name }}</span>
                    <time class="submit-date" datetime="{{ comment.created_time }}">{{ comment.created_time }}</time>
                    <div class="text">
                        {{ comment.text }}
                    </div>
                </li>
                {% empty %}
                暂无评价
                {% endfor %}
            </ul>
        </div>
    </section>
{% endblock main %}

{% block toc %}
    <div class="widget widget-content">
        <h3 class="widget-title">文章目录</h3>
        {{ post.toc|safe }}
    </div>
{% endblock toc %}

templates/blog/index.html
{% extends 'base.html' %}

{% block main %}
    {% if error_msg %}
        <p>{{ error_msg }}</p>
    {% endif %}

    {% for post in post_list %}
        <article class="post post-{{ post.pk }}">
            <header class="entry-header">
                <h1 class="entry-title">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </h1>
                <div class="entry-meta">
                    <span class="post-category"><a href="{% url 'blog:category' post.category.pk %}">{{ post.category.name }}</a></span>
                    <span class="post-date"><a href="#"><time class="entry-date" datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
                    <span class="post-author"><a href="#">{{ post.author }}</a></span>
                    <span class="comments-link"><a href="{{ post.get_absolute_url }}#comment-area">{{ post.comment_set.count }} 评论</a></span>
                    <span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }}阅读</a> </span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>{{ post.excerpt }}...</p>
                <div class="read-more cl-effect-14">
                    <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
    {% empty %}
        <div class="no-post">暂时还没有发布的文章！</div>
    {% endfor %}
    <!-- 简单分页效果
                <div class="pagination-simple">
                    <a href="#">上一页</a>
                    <span class="current">第 6 页 / 共 11 页</span>
                    <a href="#">下一页</a>
                </div>
                -->

    {% if is_paginated %}
        <div class="pagination">
            <!-- 如果当前页还有上一页，显示一个上一页的按钮 -->
            {% if first %}
                <a href="?page=1">1</a>
            {% endif %}
            {% if left %}
                {% if left_has_more %}
                    <span>...</span>
                {% endif %}
                {% for i in left %}
                    <a href="?page={{ i }}">{{ i }}</a>
                {% endfor %}
            {% endif %}
            <a href="?page={{ page_obj.number }}" style="color:red">{{ page_obj.number }}</a>
            {% if right %}
                {% for i in right %}
                    <a href="?page={{ i }}">{{ i }}</a>
                {% endfor %}
                {% if right_has_more %}
                    <span>...</span>
                {% endif %}
            {% endif %}
            {% if last %}
                <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
            {% endif %}
        </div>
    {% endif %}

{% endblock main %}